name: autoDeploy

on:
  push:
    branches: [release]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PWD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.SSH_REPOSITORY }}
            git fetch origin release
            git reset --hard origin/release
            pm2 kill
            cd ./client
            npm install
            npm run build
            cd ../server
            npm install
            npm run build
            pm2 start ./dist/app.js